import type { WebSocket } from "ws";
import { ClientSession, Game, WSMessage } from "../../types/types.js";
/* generated by server id for player in the game session, not enemy (unique id for every player) */
export const createGame = (ws: WebSocket, clients: ClientSession[], idGame: number | string, idPlayer: number | string) => {
    const createGameData: Game = { idGame: idGame, idPlayer: idPlayer };
    const createGame: WSMessage = { type: 'create_game', data: JSON.stringify(createGameData), id: 0 };

    clients.forEach(client => {
        // const createGame = JSON.stringify({ id: 0, type: 'update_room', data: JSON.stringify([]) });
        // console.log('clients: ClientSession[]: ', create);
        client.ws.send(JSON.stringify(createGame));
    });



    // ws.send(JSON.stringify(start));
}
