import type { WebSocket } from "ws";
import { ClientSession, Game, WSMessage } from "../../types/types.js";
/* generated by server id for player in the game session, not enemy (unique id for every player) */
export const createGame = (ws: WebSocket,
    idGame: number | string,
    idPlayer: number | string) => {

    const createGameData: Game = { idGame: idGame, idPlayer: idPlayer };

    const createGame: WSMessage = {
        type: 'create_game',
        data: JSON.stringify(createGameData),
        id: 0
    };
    
    ws.send(JSON.stringify(createGame));
}
